plugins { id 'com.android.application' }

android {
    namespace 'local.pd2405.exttele.prototype'
    compileSdk 35
    defaultConfig {
        applicationId 'local.pd2405.exttele.prototype'
        minSdk 33
        targetSdk 35
        versionCode 110
        versionName '1.100-photo-ruler-guides'
    }
}

dependencies { compileOnly project(':xposed-api-stubs') }
